version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          # split specs across machines 
          # record results with Cypress Cloud
          cypress-command: 'npm run cy:run --parallel --record'
          parallelism: 2